408 Prod DDL improvement, add test patches job to travis
ONSdigital/ssdc-rm-ddl pull request #103
Opened 2022-10-05 13:38 UTC by AdamHawtin

# Motivation and Context

We want our patch scripts to be tested

# What has changed

- Add scripts and job to test patch scripts against our dev postgres image

# How to test?

Check travis build
Try `make test-patches` locally

# Links

https://trello.com/c/Zyj3PlNA/408-spike-how-do-we-handle-ddl-setup-change-in-prod-2-days

2022-10-07 08:57 UTC, davidmort requested changes

2022-10-07 08:57 UTC, davidmort commented on README.md
> +Contains ground zero scripts to create all the RM database tables, as well as a script to update the DDL from the master
```suggestion
Contains ground zero scripts to create all the RM database tables, as well as a script to update the DDL from the main
```

2022-10-07 09:52 UTC, davidmort approved these changes

2022-10-10 12:17 UTC, LukeLoze1 commented on README.md
> +make pull-latest-dev-common-postgres
should this be: 
pull-latest-dev-postgres

or should it be renamed in the Makefil

2022-10-11 07:55 UTC, LukeLoze1 approved these changes

2022-10-11 12:58 UTC, merged