464 adding indexes into ddl model
ONSdigital/ssdc-rm-ddl pull request #111
Opened 2022-10-31 09:55 UTC by LukeLoze1

# Has the DDL schema changed?
*Pull requests which include schema changes should be labelled with the `schema change` label for visibility*

*The [common entity model pom.xml](ssdc-rm-common-entity-model/pom.xml) file `project.version` must be bumped
appropriately if there are any common entity code changes*

* [ ] This PR includes DDL schema changes and has been labelled correctly, bumping to new schema
  version: 
* [ ] The POM has been updated with an appropriate version bump if required

# Motivation and Context
New indexes and run the indexes on the 

# What has changed
added new patch
new file for running in GIN indexes, now run on Groundzero

# How to test?
Check patch 1st
Then run in the ddl groundzero in the env of your choice.  Has it created the indexes expected?

# Links
https://trello.com/b/VS0ZyRmj/srm

2022-11-01 08:49 UTC, AdamHawtin requested changes
The uac_qid_link qid index needs to be added to the common entity model.

2022-11-01 09:46 UTC, LukeLoze1 commented
> The uac_qid_link qid index needs to be added to the common entity model.

2022-11-01 13:27 UTC, AdamHawtin commented on ssdc-rm-common-entity-model/src/main/java/uk/gov/ons/ssdc/common/model/entity/UacQidLink.java
> +    indexes = {@Index(name = "uac_qid_idx", columnList = "qid")})
Small point but a more precise name on the index might be helpful, `uac_qid_idx` isn't clear which column it refers to

2022-11-02 09:00 UTC, AdamHawtin approved these changes
LGTM 👍

2022-11-02 16:50 UTC, ryangrundy7 approved these changes

2022-11-03 10:09 UTC, merged