621 Add create EQ flush action permission
ONSdigital/ssdc-rm-ddl pull request #116
Opened 2023-01-06 10:01 UTC by AdamHawtin

# Has the DDL schema changed?
*Pull requests which include schema changes should be labelled with the `schema change` label for visibility*

*The [common entity model pom.xml](ssdc-rm-common-entity-model/pom.xml) file `project.version` must be bumped
appropriately if there are any common entity code changes*

* [x] This PR includes DDL schema changes and has been labelled correctly, bumping to new schema
  version: `1.0.3`
* [x] The POM has been updated with an appropriate version bump if required

# Motivation and Context

Add EQ Flush action permission

# What has changed

- Add EQ Flush action permission to support actions group

# How to test?

Build and run all the branches locally, run the ATs branch. Try creating/running an EQ Flush action rule from support tool.

# Links

https://trello.com/c/sN2EG6Rh/621-eq-flushing-by-action-rule-with-rate-limiting-13

# Screenshots (if appropriate):

2023-01-11 15:23 UTC, davidmort approved these changes

2023-01-12 08:28 UTC, LukeLoze1 reviewed
Does 'make dev-build' need running?

2023-01-13 11:11 UTC, davidmort requested changes

2023-01-13 11:11 UTC, davidmort commented on groundzero_ddl/ddl_version.sql
> +INSERT INTO ddl_version.version (version_tag, updated_timestamp) VALUES ('v1.0.3', current_timestamp);
does the version number in the patch_database.py script need to be updated to 1.0.3?

2023-01-13 14:42 UTC, davidmort approved these changes

2023-01-17 13:51 UTC, LukeLoze1 approved these changes

2023-01-18 09:50 UTC, merged