create GIN index on cases sample
ONSdigital/ssdc-rm-ddl pull request #12
Opened 2021-07-14 13:42 UTC by LukeLoze1

# Motivation and Context
Add an Index to cases sample

# What has changed
Added a new Index

# How to test?
Spin up and environment, add a large sample file.  Try a search using the related UI tool changes, how fast is it?  Then run in the new DDL, compare the speed.

# Links
https://trello.com/c/RlCtolCu/2450-ops-tool-case-search-13

2021-07-16 14:17 UTC, NickGrantONS requested changes
the `build_groundzero_ddl.sh` will just wipe this change out. You shouldn't hand-modify machine-generated files. The index will have to be applied manually unless you can figure out how to tell JPA/Hibernate to create the GIN index on the entity

2021-07-19 11:37 UTC, NickGrantONS requested changes
This will not work.

Ground zero prepares a brand new database. That brand new database will not have the GIN index in it. How will the GIN index get it in? It will not get in the brand new database.

This PR will only put the GIN index into OLD databases. We don't care about old databases at this stage, because we are not in any data preservation environments.

Either find out how to create the GIN index using Hibernate/JPA or create a script to apply the index manually.

2021-07-19 13:28 UTC, NickGrantONS approved these changes
LGTM 👍

2021-07-19 13:47 UTC, ryangrundy7 approved these changes

2021-07-19 14:04 UTC, merged