Added patch to update replacement UAC templates
ONSdigital/ssdc-rm-ddl pull request #135
Opened 2023-05-31 16:28 UTC by KieranWardle

# Has the DDL schema changed?
*Pull requests which include schema changes should be labelled with the `schema change` label for visibility*

*The [common entity model pom.xml](ssdc-rm-common-entity-model/pom.xml) file `project.version` must be bumped
appropriately if there are any common entity code changes*

* [ √] This PR includes DDL schema changes and has been labelled correctly, bumping to new schema
  version: 1.0.12
* [ ] The POM has been updated with an appropriate version bump if required

# Motivation and Context
We need to remove last name from our UAC replacement email templates

# What has changed
Added patch to update templates and notify template IDs

# How to test?
make dev-build
DB_PORT=6432 pipenv run python patch_database.py

Check rows in local DB  email_template table

2023-06-02 08:20 UTC, liamtoozer requested changes
The patches look good but think the `groundzero_ddl/packcode_templates/email_templates.sql` needs to be updated as well

2023-06-02 08:20 UTC, liamtoozer commented on dev-common-postgres-image/init.sql
> +('RE_UAC_CY_CRIS', 'CRIS Reminder with UAC - Bilingual Welsh', 'bc35ebcd-63ca-4a90-aa4c-eea3e85ed506', null, '["__uac__","PORTAL_ID","COLLEX_CLOSE_DATE","FIRST_NAME","__sensitive__.LAST_NAME"]')
I think the pack codes here need to reflect the changes in this patch as well

2023-06-05 08:18 UTC, ryangrundy7 commented on dev-common-postgres-image/init.sql
This file needs to be updated with the new template ids as well. Keep getting changes when running `make dev-build`
```
-('UR_EN_CRIS', 'CRIS UAC Replacement - English', '3543bcf5-6986-4d8d-80ab-79fba4d3f050', null ,'["__uac__","PORTAL_ID","FIRST_NAME","__sensitive__.LAST_NAME"]'),
-('UR_CY_CRIS', 'CRIS UAC Replacement - Bilingual Welsh', 'cfe91e5d-19a9-4325-8e4f-0bcbd1dcacff', null ,'["__uac__","PORTAL_ID","FIRST_NAME","__sensitive__.LAST_NAME"]'),
+('UR_EN_CRIS', 'CRIS UAC Replacement - English', '1b50c02e-ba9e-42d5-9f1a-aa6f6c28fe97', null ,'["__uac__","PORTAL_ID","FIRST_NAME"'),
+('UR_CY_CRIS', 'CRIS UAC Replacement - Bilingual Welsh', '887accef-eac5-4842-b280-fe5f8af16c14', null ,'["__uac__","PORTAL_ID","FIRST_NAME"'),

```

2023-06-05 08:30 UTC, ryangrundy7 requested changes
When bringing up docker-dev I see this error in the postgres logs
```
psql:/docker-entrypoint-initdb.d/init.sql:615: ERROR:  invalid input syntax for type json
LINE 6: ...h', '1b50c02e-ba9e-42d5-9f1a-aa6f6c28fe97', null ,'["__uac__...
                                                             ^
DETAIL:  The input string ended unexpectedly.
CONTEXT:  JSON data, line 1: ["__uac__","PORTAL_ID","FIRST_NAME"
INSERT 0 4
2023-06-05 08:28:28.097 UTC [82] ERROR:  invalid input syntax for type json at character 944
2023-06-05 08:28:28.097 UTC [82] DETAIL:  The input string ended unexpectedly.
2023-06-05 08:28:28.097 UTC [82] CONTEXT:  JSON data, line 1: ["__uac__","PORTAL_ID","FIRST_NAME"
2023-06-05 08:28:28.097 UTC [82] STATEMENT:  INSERT INTO casev3.email_template (pack_code, description, notify_template_id, metadata, template) VALUES
	('NE_EN_CRIS', 'CRIS Notification - English', '55c23289-6331-47f2-89b9-5b88bcfc3f41', null ,'["__uac__","PORTAL_ID","COLLEX_OPEN_DATE","COLLEX_CLOSE_DATE","FIRST_NAME","__sensitive__.LAST_NAME"]'),
	('NE_CY_CRIS', 'CRIS Notification - Bilingual Welsh', 'acd97184-b282-4ff9-98cf-ba14bf74c2f8', null ,'["__uac__","PORTAL_ID","COLLEX_OPEN_DATE","COLLEX_CLOSE_DATE","FIRST_NAME","__sensitive__.LAST_NAME"]'),
	('RE_EN_CRIS', 'CRIS Reminder - English', '8cf30001-0c06-4da4-b49d-1df975a1123a', null ,'["PORTAL_ID","COLLEX_CLOSE_DATE","FIRST_NAME","__sensitive__.LAST_NAME"]'),
	('RE_CY_CRIS', 'CRIS Reminder - Bilingual Welsh', '42af756c-7239-4486-b67d-ce2c6c4a7f9b', null ,'["PORTAL_ID","COLLEX_CLOSE_DATE","FIRST_NAME","__sensitive__.LAST_NAME"]'),
	('UR_EN_CRIS', 'CRIS UAC Replacement - English', '1b50c02e-ba9e-42d5-9f1a-aa6f6c28fe97', null ,'["__uac__","PORTAL_ID","FIRST_NAME"'),
	('UR_CY_CRIS', 'CRIS UAC Replacement - Bilingual Welsh', '887accef-eac5-4842-b280-fe5f8af16c14', null ,'["__uac__","PORTAL_ID","FIRST_NAME"'),
	('RE_UAC_EN_CRIS', 'CRIS Reminder with UAC - English', 'd0224400-4894-4bdd-b0bc-839972641327', null, '["__uac__","PORTAL_ID","COLLEX_CLOSE_DATE","FIRST_NAME","__sensitive__.LAST_NAME"]'),
	('RE_UAC_CY_CRIS', 'CRIS Reminder with UAC - Bilingual Welsh', 'bc35ebcd-63ca-4a90-aa4c-eea3e85ed506', null, '["__uac__","PORTAL_ID","COLLEX_CLOSE_DATE","FIRST_NAME","__sensitive__.LAST_NAME"]')
	ON CONFLICT (pack_code) DO UPDATE SET (description, notify_template_id, metadata, template) = (EXCLUDED.description, EXCLUDED.notify_template_id, EXCLUDED.metadata, EXCLUDED.template);

```

2023-06-06 10:09 UTC, liamtoozer approved these changes

2023-06-06 10:25 UTC, ryangrundy7 approved these changes
Looks good :+1:

2023-06-06 11:02 UTC, merged