Replace Queue With Subscription
ONSdigital/ssdc-rm-ddl pull request #20
Opened 2021-08-19 08:50 UTC by LeoKHoward

# Motivation and Context
Since changing to pub/sub, terminology is out of date so queue needs to become subscription

# What has changed
Changed queue to subscription

# Links
https://trello.com/c/XPwwUY31

2021-08-19 08:50 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Change exception manager to have more meaningful error fields (5)](https://trello.com/c/XPwwUY31/2662-change-exception-manager-to-have-more-meaningful-error-fields-5)

2021-08-19 12:34 UTC, ryangrundy7 requested changes
Don't think you meant to remove send_to_our_project

2021-08-19 12:34 UTC, ryangrundy7 commented on groundzero_ddl/casev3.sql
> -        send_to_our_project boolean,
Don't think you meant to remove this?

2021-08-19 15:42 UTC, NickGrantONS commented on groundzero_ddl/casev3.sql
> -        send_to_our_project boolean,
it's ok... gone now anyway

2021-08-19 15:42 UTC, NickGrantONS approved these changes

2021-08-23 10:09 UTC, ryangrundy7 approved these changes

2021-08-23 10:10 UTC, merged