SDCSRM-441 HMS Email Templates
ONSdigital/ssdc-rm-ddl pull request #200
Opened 2024-05-16 13:39 UTC by dbanks91

# Has the DDL schema changed?
*Pull requests which include schema changes should be labelled with the `schema change` label for visibility*

*The [common entity model pom.xml](ssdc-rm-common-entity-model/pom.xml) file `project.version` must be bumped
appropriately if there are any common entity code changes*

* [x] This PR includes DDL schema changes and has been labelled correctly, bumping to new schema
  version: 1.1.1
* [ ] The POM has been updated with an appropriate version bump if required

# Motivation and Context
We needed to add email templates for HMS

# What has changed
- Added templates

# How to test?
- Check it all looks ok and matches with the info on confluence page linked on the Jira Card

# Links
[SDCSRM-441](https://jira.ons.gov.uk/browse/SDCSRM-441)

# Screenshots (if appropriate):

2024-05-16 15:26 UTC, ryangrundy7 commented on dev-common-postgres-image/init.sql
> +('MRE_EN_HMS', 'Main Reminder Email', '1b46b5e1-e247-48b3-b3b3-bf949efd79cb', 'Office_for_National_Statistics_surveys_NHS', null, '["__uac__", "PORTAL_ID", "COLLEX_OPEN_DATE", "COLLEX_CLOSE_DATE", "F
The notify service ref `Office_for_National_Statistics_surveys_NHS` doesn't exist. It's something we add as part of the notify config. Currently the config is using `Office_for_National_Statistics_surveys_UKHSA` for the gov notify service we use. It's something we need to change as part of this. If it's NHS branding on the template then we should look to rename it from `Office_for_National_Statistics_surveys_UKHSA` to `Office_for_National_Statistics_surveys_NHS`

2024-05-16 15:28 UTC, ryangrundy7 requested changes
Notify service ref is incorrect so this won't work. We need to either make it the ukhsa one it currently is or change it in the notify config as part of this. Probably best to so the latter

2024-05-23 08:46 UTC, AdamHawtin approved these changes

2024-05-23 09:07 UTC, ryangrundy7 approved these changes

2024-05-23 10:13 UTC, merged