Regenerate DDL (add print file row table)
ONSdigital/ssdc-rm-ddl pull request #26
Opened 2021-09-07 12:35 UTC by AdamHawtin

# Motivation and Context
WIP

# What has changed
- 
- Regenerate DDL (add print file row table)

# How to test?

WIP

# Links
https://trello.com/c/Lni8psPO/2691-productionise-database-based-print-file-building-spike-8

2021-09-10 07:36 UTC, NickGrantONS commented on groundzero_ddl/casev3.sql
> +       foreign key (action_rule_id)
foreign key on action rule not required

2021-09-10 07:36 UTC, NickGrantONS commented on groundzero_ddl/casev3.sql
> +        action_rule_id uuid,
relationship with action rule not required

2021-09-10 07:37 UTC, NickGrantONS commented on patches/100_add_print_file_row_table.sql
> +-- Number: 100
we already have a patch 100 merged into `main`

2021-09-10 07:37 UTC, NickGrantONS commented on patches/100_add_print_file_row_table.sql
> +    action_rule_id uuid,
remove the action rule - not needed

2021-09-10 07:37 UTC, NickGrantONS commented on patches/100_add_print_file_row_table.sql
> +            references casev3.action_rule;
remove the action rule - not needed

2021-09-10 07:37 UTC, NickGrantONS commented on groundzero_ddl/ddl_version.sql
> +INSERT INTO ddl_version.patches (patch_number, applied_timestamp) VALUES (100, current_timestamp);
we already have a patch 100

2021-09-10 07:37 UTC, NickGrantONS requested changes
See comments

2021-09-10 10:09 UTC, NickGrantONS approved these changes

2021-09-13 12:25 UTC, ryangrundy7 approved these changes

2021-09-13 12:39 UTC, merged