2884 Add RM UI group setup scripts
ONSdigital/ssdc-rm-ddl pull request #40
Opened 2021-10-01 09:34 UTC by AdamHawtin

# Motivation and Context
We need some groups defined for day to day RM support and elevated write access roles for the support tool UI/r-ops.

# What has changed
- Add UI permissions scripts

# How to test?
Check the lists of permissions make sense, RM SUPPORT should be all the global read only permissions and RM ELEVATED should have write access but only on our non prototype features.

# Links
https://trello.com/c/ZxqCN8wb/2884-productionise-support-tool-set-up-groups-3

2021-10-01 11:44 UTC, liamtoozer approved these changes

2021-10-01 11:50 UTC, NickGrantONS approved these changes
I think we should remove all print and fulfilment activities, or include them all... not have some and not others.

Have tested though and these groups work great.

2021-10-01 12:15 UTC, AdamHawtin commented
@NickGrantONS I've got rid of all permissions relating to print and or fulfilments 👍

2021-10-01 14:51 UTC, NickGrantONS approved these changes
I have retested since you removed the print/fulfilment permissions and they still work using the updated Support Tool: https://github.com/ONSdigital/ssdc-rm-support-tool/pull/100

2021-10-01 14:56 UTC, NickGrantONS commented on ui-permissions/RM-Elevated-Permissions.sql
> +INSERT INTO casev3.user_group_permission (id, authorised_activity, group_id, survey_id) VALUES ('376e3c34-1b3f-464c-aaa0-f3bd77960563', 'CREATE_PRINT_TEMPLATE', 'e9ed16cb-8589-435b-898b-38c038bcdaaf'
should remove this print permission

2021-10-01 14:57 UTC, NickGrantONS commented on ui-permissions/RM-Support-Permissions.sql
> +INSERT INTO casev3.user_group_permission (id, authorised_activity, group_id, survey_id) VALUES ('fe549c89-961a-4191-b359-636143dc4c50', 'LIST_ALLOWED_PRINT_TEMPLATES_ON_ACTION_RULES', 'b19a77bd-6a02-
should remove this print permission

2021-10-01 14:57 UTC, NickGrantONS requested changes
oops spoke too soon... 2 print permissions to remove

2021-10-04 07:29 UTC, NickGrantONS requested changes
I had to remove `LIST_ALLOWED_PRINT_TEMPLATES_ON_ACTION_RULES` but it's all working just fine

2021-10-04 07:40 UTC, NickGrantONS approved these changes
Tested it and it works great!

2021-10-04 07:41 UTC, merged