New script to remove global permissions that hav been created against…
ONSdigital/ssdc-rm-ddl pull request #77
Opened 2021-12-09 16:14 UTC by gavinleeedwards

# Motivation and Context
The UI previously allowed users to add a global permission to a group, but against a survey.  For example, you could add LIST_SURVEYS against a specific survey but LIST_SURVEYS is a global permission so it won't work when created against a survey.  This script removes the incorrect permissions.  A fix (currently in PR) will stop this happening in future.

# What has changed
- New script to be manually run in the db.  It removes the permission from groups where the permission is global but has been created against a survey.  
- The list of global permissions is from here: https://github.com/ONSdigital/ssdc-rm-ddl/pull/75/files

# How to test?
- Amend the script to a `SELECT *` rather than `DELETE` then run it in an environment to check that the correct rows will be deleted.

# Links
- https://trello.com/c/MPwwVCGf

2021-12-09 16:14 UTC, gavinleeedwards commented
![](https://github.trello.services/images/mini-trello-icon.png) [Global/Survey permissions in Integration env - Script to avoid full data wipe (3)](https://trello.com/c/MPwwVCGf/3166-global-survey-permissions-in-integration-env-script-to-avoid-full-data-wipe-3)

2021-12-10 08:14 UTC, hbrace requested changes

2021-12-10 08:14 UTC, hbrace commented on ui-permissions/remove-global-rule-where-survey-is-not-null.sql
> +SELECT * FROM casev3.user_group_permission
Should be a delete?

2021-12-10 09:17 UTC, gavinleeedwards commented on ui-permissions/remove-global-rule-where-survey-is-not-null.sql
> +SELECT * FROM casev3.user_group_permission
Argh, good spot.  Changed.

2021-12-10 10:37 UTC, hbrace approved these changes

2021-12-10 11:00 UTC, LukeLoze1 approved these changes

2021-12-10 11:57 UTC, merged