3277 - Add PMD and errorprone checks
ONSdigital/ssdc-rm-ddl pull request #91
Opened 2022-02-21 16:45 UTC by liamtoozer

# Motivation and Context

We can introduce PMD and ErrorProne code analysis/compile tools to our Java apps. Drawing from [this spike branch](https://github.com/ONSdigital/ssdc-rm-response-operations/pull/78/files) and adding some additional bits.

I’ve put a `<failurePriority>`  of `3` for PMD (scale of 1 - 5, with `1` being 'severe'), so it will fail on anything over a medium level severity. Anything below this level will output as a warning. I’ve set it at a level that seems sensible, but it’s debatable!

# What has changed

* Add PMD ignore file for code to be ignored for now, but to investigate later 
* Fix some errors & warnings from PMD
* Add `check` target to Makefile
* Update Travis checks

# How to test?

* If you want to see some of the PMD failures, comment out the lines in `exclude-pmd.propeties` file.
* Check to see the tools pick up the issues as expected.
* Run ATs, should still pass.

# Links

https://trello.com/c/Y4aAAwHb/3277-java-checks-8

2022-02-21 16:45 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Java Checks (8)](https://trello.com/c/Y4aAAwHb/3277-java-checks-8)

2022-02-22 15:47 UTC, ryangrundy7 requested changes
Seeing these failures for the repo
```
[INFO]
[INFO] --- maven-pmd-plugin:3.16.0:check (default) @ ssdc-rm-ddl ---
[INFO] PMD version: 6.42.0
[INFO] PMD Warning: uk.gov.ons.ssdc.common.validation.ColumnValidator:28 Rule:UseVarargs Priority:4 Consider using varargs for methods or constructors which take an array the last parameter..
[INFO] PMD Warning: uk.gov.ons.ssdc.common.validation.InSetRule:13 Rule:UseVarargs Priority:4 Consider using varargs for methods or constructors which take an array the last parameter..
[INFO] PMD Failure: uk.gov.ons.ssdc.common.validation.ColumnValidator:28 Rule:ArrayIsStoredDirectly Priority:3 The user-supplied array 'rules' is stored directly..
[INFO] PMD Failure: uk.gov.ons.ssdc.common.validation.ColumnValidator:70 Rule:UseCollectionIsEmpty Priority:3 Substitute calls to size() == 0 (or size() != 0, size() > 0, size() < 1) with calls to isEmpty().
[INFO] PMD Failure: uk.gov.ons.ssdc.common.validation.ColumnValidator:86 Rule:MethodReturnsInternalArray Priority:3 Returning 'rules' may expose an internal array..
[INFO] PMD Failure: uk.gov.ons.ssdc.rm.ddl.Application:25 Rule:AvoidPrintStackTrace Priority:3 Avoid printStackTrace(); use a logger call instead..
[INFO] PMD Failure: uk.gov.ons.ssdc.rm.ddl.Application:37 Rule:SystemPrintln Priority:2 System.out.println is used.
[INFO] PMD Failure: uk.gov.ons.ssdc.rm.ddl.Application:39 Rule:SystemPrintln Priority:2 System.out.println is used.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.492 s
[INFO] Finished at: 2022-02-22T15:46:13Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.16.0:check (default) on project ssdc-rm-ddl: You have 6 PMD violations and 2 warnings. For more details see: /Users/grundr/Projects/SSDC/ssdc-rm-docker-dev/PR_DIR/3277-java-checks/ssdc-rm-ddl/target/pmd.xml -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-ru
```

2022-02-22 15:58 UTC, gavinleeedwards approved these changes

2022-02-23 09:42 UTC, gavinleeedwards requested changes
The checks also need to go into the pom file within ssdc-rm-common-entity-model, as `make dev-install-common` doesn't run the checks.

2022-02-24 15:22 UTC, gavinleeedwards approved these changes

2022-02-25 09:11 UTC, ryangrundy7 approved these changes

2022-02-25 10:40 UTC, merged