3321 case processor double processing a fulfilment request
ONSdigital/ssdc-rm-ddl pull request #92
Opened 2022-03-08 13:21 UTC by LukeLoze1

# Motivation and Context
Add MessageId to fulfilmentToProcess, in order to stop dupe processing

https://trello.com/c/W17T8Mzc/3321-case-processor-double-processing-a-fulfilment-request-5

2022-03-11 07:22 UTC, AdamHawtin requested changes

2022-03-11 07:22 UTC, AdamHawtin commented on patches/800_add_message_id_to_fulfilment_to_process.sql
> +    ADD COLUMN IF NOT EXISTS message_id uuid NOT NULL
The migration is missing the `unique` constraint

2022-03-14 10:26 UTC, ryangrundy7 approved these changes

2022-03-15 13:20 UTC, AdamHawtin approved these changes
LGTM 👍

2022-03-15 16:39 UTC, merged